spring.application.name=OHI
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.nl.miwnn.cohort19.Sara=info

#fix later
spring.datasource.url=jdbc:mysql://localhost:3306/ohi
spring.datasource.username=userOhi
spring.datasource.password=userOhiPW

